server:
  port: 9001
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: auto
        consumers-per-queue: 1
