spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #  type-aliases-package: com.yxxmg.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.yxxmg.handler
server:
  port: 8081