server:
  port: 8811
lock4j:
  expire: 30000 # 锁的过期时间，单位毫秒
  retry-interval: 1000 # 重试间隔，单位毫秒
  lock-key-prefix: "lock4j" # 锁的key前缀
  acquire-timeout: 5000 # 获取锁的超时时间，单位毫秒
  primary-executor: com.baomidou.lock.executor.RedissonLockExecutor
  #  primary-executor: com.baomidou.lock.executor.RedisTemplateLockExecutor
  #  primary-executor: com.baomidou.lock.executor.ZookeeperLockExecutor


